language: node_js
node_js:
- 8
cache:
  directories:
  - node_modules
script:
- npm run build
- npm test
before_deploy:
- cd build
- tag=$(git tag --points-at $TRAVIS_COMMIT | tail -1)
- tar cf ../$tag.tar *
- cd ..
- if [[ -n "$(git branch --contains $TRAVIS_COMMIT | grep master)" ]]; then prerelease=false; else prerelease=true; fi
deploy:
  provider: releases
  api_key:
    secure: bvitls6cl0YNtxd17oSx9yEEcgPJC7D4d5F1FzjUbWAQKxERh7qGHwa7OmNA8uym0GsxydIMhzPFaGR4/VmEnngb/ExdJn/d/t/2Agu1xJ3ua/hzYzOjua6/6fewfenU7vHKkRDilZlrVVXGaFhxGshwG0beXFWvQxQj8txGjs34GnZJ5vYnP7PzpYaHCPttQMIUG0jur9YebTiZf6x7sHmEHyJ1R5PLxe/PcLjxctV3H8Xm3DJdtMImsDLKxWCL7BpdqYMFCctjQEmL4TRwOJer3Z2RJZTDjYsi6Lx3Zuf5FvuoctP68FHrg85QXpSXgrbPeukw+lQsssqONB0FUGfOIjT5QEgS9xXZpdIFFBD3fjUh7L7qs7I4XdREd4PEytnPrYkxo9iXqpnpnNWAOpMb+Op61rJepFITGIYKWa0Iyg+5LSRiv0A+WzubpsGhikDer5pSs3d5dibjxFIRXMMXZlZHUyUkPZUovT/Mkdz6iw65EM9hw6zM0hDY53pv6GsfTUHkBFz28mOjy6M40MCYiknf4EyEN5wQ8n/cabfBOBwjO+/eQ0E9+YMH5WZoipLHdPpY9zhntZRgiRfWabIwPTYNPQKG3D0KFXRmaFb3fsNLRkPxGjAADvYA9CXhG34IO58i0t9j8CDSVwwTCzLUX5WpjTTA5wbI9gaCxO8=
  file: $tag.tar
  skip_cleanup: true
  on:
    tags: true
  prerelease: $prerelease
