export const ABORT_COLLECTIONS = `ABORT_COLLECTIONS`
export const ERROR_COLLECTIONS = `ERROR_COLLECTIONS`
export const START_COLLECTIONS = `START_COLLECTIONS`
export const UPDATE_COLLECTIONS = `UPDATE_COLLECTIONS`