export const ABORT_PERMISSIONS = `ABORT_PERMISSIONS`
export const ERROR_PERMISSIONS = `ERROR_PERMISSIONS`
export const START_PERMISSIONS = `START_PERMISSIONS`
export const UPDATE_PERMISSIONS = `UPDATE_PERMISSIONS`