import React, { Component } from 'react'
import { connect } from 'react-redux'

import { getResources, updateContent } from 'redux/actions'

import ContentSettings from './contentSettings/ContentSettings'
// import Content from 'models/Content'

import {
	Container,
	Preview,
	EditButton,
	Icon,
	TitleEdit,
	PublishButton,
	Thumbnail
} from './styles'

import { objectIsEmpty, diff } from 'js/util'

/**
 * DO NOT EDIT THIS FILE UNLESS YOU KNOW WHAT YOU'RE DOING
 */

class Overview extends Component {

	constructor(props) {
		super(props)

		this.state = {
			editing: false,
			content: props.content,
			resource: null
		}

		this.log = true

		if (this.log) console.warn(`Overview: constructor`)
	}

	shouldComponentUpdate = (nextProps, nextState) => {

		if (this.log) console.groupCollapsed(`Overview: shouldComponentUpdate`)

		const propDiff = diff(this.props, nextProps)
		const stateDiff = diff(this.state, nextState)

		if (this.log) console.log(`props changes:`, propDiff)
		if (this.log) console.log(`state changes:`, stateDiff)

		const resourcesFetched = this.props.resourceCache.lastFetched !== nextProps.resourceCache.lastFetched
		const resourceStateChanged = stateDiff.hasOwnProperty(`resource`)

		if (this.log) {
			console.table({
				resourcesFetched: {
					value: resourcesFetched
				},
				resourceStateChanged: {
					value: resourceStateChanged
				}
			})
		}

		const changed = resourcesFetched
			|| resourceStateChanged

		if (this.log) console.log(`%c ${changed ? `RENDER` : `NO RENDER`} `, `background: ${changed ? `Maroon` : `Teal`}`)

		if (this.log) console.groupEnd(`Overview: shouldComponentUpdate`)

		return changed
	}

	handlers = {
		handleEdit: e => {
			e.preventDefault()

			const { content, editing } = this.state

			if (editing) {
				this.props.updateContent(content)
				this.setState({
					editing: false
				})
			} else {
				this.props.getResources(this.props.content.resourceId)
				this.setState({
					editing: true
				})
			}

		},
		handleNameChange: e => {
			this.setState({
				content: {
					...this.state.content,
					name: e.target.value,
					resource: {
						...this.state.content.resource,
						title: e.target.value
					}
				}
			})
		},
		handleToggle: e => {
			const { key } = e.target.dataset
			this.setState({
				content: {
					...this.state.content,
					settings: {
						...this.state.content.settings,
						[key]: !this.state.content.settings[key]
					}
				}
			})
		},
		handleDescription: e => {
			const { content } = this.state
			this.setState({
				content: {
					...content,
					description: e.target.value,
					resource: {
						...content.resource,
						description: e.target.value
					},
					settings: {
						...content.settings,
						description: e.target.value
					}
				}
			})
		},
		handleRatio: e => {
			const { content } = this.state
			const { settings } = content

			this.setState({
				content: {
					...content,
					settings: {
						...settings,
						aspectRatio: e.target.value
					}
				}
			})
		},
		addTag: newTags => {
			const { keywords } = this.state.content.resource
			const tags = [...newTags, ...keywords]
			this.setState({
				content: {
					...this.state.content,
					resource: {
						...this.state.content.resource,
						keywords: tags
					}
				}
			})
		},
		removeTag: e => {
			e.preventDefault()
			this.setState({
				content: {
					...this.state.content,
					resource: {
						...this.state.content.resource,
						keywords: this.state.content.resource.keywords.filter(item => item !== e.target.dataset.value)
					}
				}
			})
		},
		togglePublish: e => {
			e.preventDefault()
			this.setState({
				content: {
					...this.state.content,
					published: !this.state.content.published
				}
			})
		}
	}

	render() {

		if (this.log) console.error(`Overveiw: render`)

		const { editing, content } = this.state

		if (content === undefined) return null

		const { handleNameChange, handleEdit, togglePublish } = this.handlers

		const {
			allowDefinitions,
			showCaptions,
			showAnnotations
		} = content.settings

		const { isFetching } = this.props.resourceCache

		return (
			<Container>
				<Preview>
					<div>
						<Thumbnail src={content.thumbnail} />
					</div>
					<div>
						{editing ?
							<TitleEdit type='text' value={content.name} onChange={handleNameChange} />
							:
							<h4>{content.name}</h4>}
						<ul>
							<Icon className='translation' checked={allowDefinitions} />
							<Icon className='captions' checked={showCaptions} />
							<Icon className='annotations' checked={showAnnotations} />
						</ul>
						{
							editing ?
								<PublishButton published={content.published} onClick={togglePublish}>{content.published ? `Unpublish` : `Publish`}</PublishButton>
								:
								<em>{content.published ? `Published` : `Unpublished`}</em>
						}
					</div>
					<div>
						<EditButton onClick={handleEdit}>{editing ? `Save` : `Edit`}</EditButton>
					</div>
				</Preview>
				{
					editing ?
						isFetching || <ContentSettings handlers={this.handlers} content={this.state.content} editing={editing} />
						: null
				}
			</Container>
		)
	}

	componentDidUpdate = (prevProps, prevState) => {

		if (this.log) console.warn(`Overview: componentDidUpdate`)

		if (this.log) console.groupCollapsed(`Overview: componentDidUpdate`)

		const propDiff = diff(prevProps, this.props)
		const stateDiff = diff(prevState, this.state)

		if (this.log) console.log(`props changes:`, propDiff)
		if (this.log) console.log(`state changes:`, stateDiff)

		const resourcePropDiff = propDiff.resourceCache === undefined ? null : propDiff.resourceCache
		const resourceStateDiff = stateDiff.resource === undefined ? null : stateDiff.resource

		const resourcePropChanged = resourcePropDiff === null ? false : !objectIsEmpty(resourcePropDiff)
		const resourceStateChanged = resourceStateDiff === null ? false : !objectIsEmpty(resourceStateDiff)

		if (this.log) {
			console.table({
				resourcePropChanged: {
					value: resourcePropChanged
				},
				resourceStateChanged: {
					value: resourceStateChanged
				}
			})
		}

		if (resourcePropChanged) {
			if (this.log) console.log(`%c SETTING STATE `, `background: Teal`)

			this.setState({
				resource: this.props.resourceCache.resources[this.state.content.resourceId]
			})
		}

		if (resourceStateChanged) {
			if (this.log) console.log(`%c FETCHING CONTENT `, `background: Maroon`)
			this.props.getResources(this.state.resource.id)
		}

		if (!resourcePropChanged && !resourceStateChanged)
			if (this.log) console.log(`%c NO ACTION `, `background: Gray`)

		if (this.log) console.groupEnd(`Overview: componentDidUpdate`)

	}

}

const mapStateToProps = state => ({
	resourceCache: state.resourceCache,
	contentCache: state.contentCache
})

const mapDispatchToProps = {
	getResources,
	updateContent
}

export default connect(mapStateToProps, mapDispatchToProps)(Overview)
