# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: yvideo frontend CI

on:
  push:
    branches: [ develop, build ]
  pull_request:
    branches: [ develop, build ]
  # repository_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm install
    - run: npm test
    - run: npm build

# dispatch frontend to backend
      # - name: Dispatch initiating repository event
      #   run: |
      #     curl -X POST https://api.github.com/repos/youthrich40/y-video-back-end/dispatches \
      #     -H 'Accept: application/vnd.github.everest-preview+json' \
      #     -u ${{ secrets.YVIDEO_ACCESS_TOKEN }} \
      #     --data '{"event_type": "yvideo-frontend", "client_payload": { "repository": "'"$GITHUB_REPOSITORY"'" }}'

# receive dispatch from frontend (add this to backend)
      # - name: Event Information
      #       run: |
      #         echo "Event '${{ github.event.action }}' received from '${{ github.event.client_payload.repository }}'"